name: Deploy Coffee Shop

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Add Environment Variables
      run: |
        echo "LD_CLIENT_SIDE_KEY=${{ secrets.LD_CLIENT_SIDE_KEY }}" >> .env
        echo "LD_SERVER_SDK_KEY=${{ secrets.LD_SERVER_SDK_KEY }}" >> .env
        echo "LD_API_AUTH=${{ secrets.LD_API_AUTH }}" >> .env
        
    - name: Build and Start
      run: npm start
